# Generated by Django 2.2.1 on 2019-05-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celular',
            options={'verbose_name': 'Celular', 'verbose_name_plural': 'Celulares'},
        ),
        migrations.AddField(
            model_name='celular',
            name='camarafrontal',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='celular',
            name='camaratrasera',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='celular',
            name='memoria',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
