# Generated by Django 2.2.1 on 2019-05-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190521_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='srcimg',
            field=models.CharField(default="{%static 'core/img/'%}", max_length=100),
        ),
        migrations.AlterField(
            model_name='celular',
            name='camarafrontal',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='celular',
            name='camaratrasera',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='celular',
            name='memoria',
            field=models.CharField(default='', max_length=20),
        ),
    ]
