# Generated by Django 2.2.1 on 2019-05-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190522_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='srcimg',
            field=models.CharField(default="{% static 'core/img/' %}", max_length=100),
        ),
    ]
