# Generated by Django 2.2.1 on 2019-05-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190522_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, unique=True)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('Total', models.IntegerField(default=0)),
            ],
        ),
    ]
