# Generated by Django 2.2.1 on 2019-05-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='srcimg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
