# Generated by Django 2.2.1 on 2019-05-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190522_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
