# Generated by Django 2.2 on 2019-05-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_celular_idpaypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='idpaypalcarrito',
            field=models.CharField(default='', max_length=20),
        ),
    ]
